//! 5x5 **tiltak-driven** self-play training-data generator → "TAK6" binpack.
//!
//! Unlike [`crate::datagen`] (which self-plays with Topaz's own search on Board6), this module
//! drives the **tiltak** engine as a TEI subprocess to label 5x5 positions for the double-black-stack
//! variant (komi 0). The black-stack rule only fires at ply 1, which tiltak (standard rules) rejects,
//! so **Topaz generates the opening** (forced `2xx` + random flats) and hands tiltak a TPS at
//! `move_num >= 2`; tiltak then plays out standard Tak, giving a move + win-probability per ply.
//!
//! Per position we record `(BoardData5, score)` where `score` is the side-to-move-relative eval such
//! that `sigmoid(score/400) = p` (tiltak's STM win-prob), then backfill the game's WDL result. The
//! on-disk format is byte-identical to [`crate::datagen`] (see that module's header) so the same
//! `topaz checkdata` validator and the bullet trainer (`examples/tak5.rs`) consume it.

use crate::board::{Board5, TakBoard};
use crate::eval::{build_nn_repr5, BoardData5, NNUE5};
use crate::generate_all_moves;
use crate::search::{search, SearchInfo};
use crate::transposition_table::HashTable;
use crate::{GameMove, GameResult, Piece, Position};

use rand_core::{RngCore, SeedableRng};
use rand_xoshiro::Xoshiro256PlusPlus;
use std::fs::File;
use std::io::{self, BufRead, BufReader, BufWriter, Write};
use std::process::{Child, ChildStdin, ChildStdout, Command, Stdio};
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::{mpsc, Arc};
use std::thread;
use std::time::Instant;

/// "TAK6" as a big-endian u32; written little-endian to match the trainer's native-endian read.
const TAK_MAGIC: u32 = u32::from_be_bytes(*b"TAK6");
const CHUNK_HEADER_SIZE: usize = 8;
/// Flush a chunk once its body reaches roughly this size (closed only on entry boundaries).
const TARGET_CHUNK_BYTES: usize = 8 * 1024;
/// Eval scale shared with the trainer: `sigmoid(score / EVAL_SCALE) == win_prob`.
const EVAL_SCALE: f64 = 400.0;

#[derive(Clone, Debug)]
pub struct DataGen5Config {
    /// Total number of self-play games to generate.
    pub num_games: usize,
    /// Worker threads; each owns its own tiltak subprocess.
    pub threads: usize,
    /// tiltak search budget per move (`go nodes N`).
    pub max_nodes: u64,
    /// Random opening plies generated by Topaz before tiltak takes over (includes the forced ply-1
    /// `2xx` double placement). 6 = the user's "random 6-ply" opening.
    pub random_plies: usize,
    /// Hard cap on plies per game; reaching it scores the game a draw.
    pub max_plies: usize,
    /// Half-komi passed to tiltak (`setoption HalfKomi`); 0 for the black-stack variant.
    pub half_komi: u8,
    /// Path to the tiltak TEI binary (e.g. `../tiltak/target/release/tei.exe`).
    pub tiltak_path: String,
    /// Optional opening book (TPS per line, move_num>=2). If set, games start from book positions
    /// (standard play); if None, openings are generated internally (black-stack).
    pub book_path: Option<String>,
    /// Output `.bin` path.
    pub output: String,
}

impl Default for DataGen5Config {
    fn default() -> Self {
        Self {
            num_games: 1000,
            threads: 4,
            max_nodes: 10_000,
            random_plies: 6,
            max_plies: 120,
            half_komi: 0,
            tiltak_path: "../tiltak/target/release/tei.exe".to_string(),
            book_path: None,
            output: "data5.bin".to_string(),
        }
    }
}

// ---------------------------------------------------------------------------
// TAK6 serialization (mirrors crate::datagen, typed for the size-5 BoardData)
// ---------------------------------------------------------------------------

/// Append one position as a full-snapshot entry (`plys_len = 0`) to a chunk body buffer.
fn push_entry(body: &mut Vec<u8>, data: &BoardData5, score: i16, result: u8, half_komi: u8) {
    body.push(data.caps[0]);
    body.push(data.caps[1]);
    body.push(data.white_to_move as u8);
    body.push(0); // extra_score
    body.extend_from_slice(&score.to_le_bytes());
    body.push(result);
    body.push(half_komi);
    body.push(data.data_len);
    body.push(0); // plys_len
    for i in 0..data.data_len as usize {
        // The engine's PieceSquare byte is exactly the trainer's PSquare byte.
        body.push(data.data[i].0);
    }
}

/// Wrap an accumulated entry body in a `ChunkHeader`.
fn make_chunk(body: &[u8]) -> Vec<u8> {
    let mut out = Vec::with_capacity(CHUNK_HEADER_SIZE + body.len());
    out.extend_from_slice(&TAK_MAGIC.to_le_bytes());
    out.extend_from_slice(&(body.len() as u32).to_le_bytes());
    out.extend_from_slice(body);
    out
}

/// Map a finished game's result to the side-to-move-relative label {0 = loss, 1 = draw, 2 = win}.
fn result_for(white_to_move: bool, outcome: GameResult) -> u8 {
    match outcome {
        GameResult::Draw => 1,
        GameResult::WhiteWin => {
            if white_to_move {
                2
            } else {
                0
            }
        }
        GameResult::BlackWin => {
            if white_to_move {
                0
            } else {
                2
            }
        }
    }
}

fn new_rng() -> Xoshiro256PlusPlus {
    let mut seed = [0u8; 32];
    getrandom::fill(&mut seed).expect("failed to seed rng");
    Xoshiro256PlusPlus::from_seed(seed)
}

/// Convert tiltak's STM win-probability into a side-to-move-relative score with
/// `sigmoid(score / EVAL_SCALE) == p`. Clamped to avoid infinities and stay within the trainer's
/// `|score| <= 9999` filter.
fn score_from_winprob(p: f64) -> i16 {
    let p = p.clamp(1e-3, 1.0 - 1e-3);
    let score = (EVAL_SCALE * (p / (1.0 - p)).ln()).round();
    score.clamp(-9000.0, 9000.0) as i16
}

/// Load an opening book: one TPS position per line (blank lines ignored).
fn load_book(path: &str) -> io::Result<Vec<String>> {
    let text = std::fs::read_to_string(path)?;
    let lines: Vec<String> = text
        .lines()
        .map(|l| l.trim().to_string())
        .filter(|l| !l.is_empty())
        .collect();
    if lines.is_empty() {
        return Err(io::Error::new(io::ErrorKind::InvalidData, format!("empty opening book: {path}")));
    }
    Ok(lines)
}

/// Build a game's starting board. With a book, start from a random book position (which must be at
/// `move_num >= 2` so the black-stack rule never fires — i.e. standard play). Without a book, start
/// from a fresh board and apply `random_plies` random flats (forced `2xx` at ply 1 -> black-stack).
fn start_board(book: &Option<Arc<Vec<String>>>, random_plies: usize, rng: &mut impl RngCore) -> Board5 {
    if let Some(book) = book {
        let line = &book[(rng.next_u32() as usize) % book.len()];
        Board5::try_from_tps(line).expect("book TPS should parse")
    } else {
        let mut board = Board5::new();
        for _ in 0..random_plies {
            if board.game_result().is_some() {
                break;
            }
            do_random_flat_move(&mut board, rng);
        }
        board
    }
}

/// Play one random flat placement (the forced `2xx` at ply 1 is itself a flat, so it is preserved).
/// Inlined here (rather than using `Board6::do_random_flat_move`) to keep this module size-isolated;
/// `pub(crate)` so `balance5` can reuse it.
pub(crate) fn do_random_flat_move(board: &mut Board5, rng: &mut impl RngCore) {
    let mut moves: Vec<GameMove> = Vec::new();
    generate_all_moves(board, &mut moves);
    let flats: Vec<GameMove> = moves
        .iter()
        .copied()
        .filter(|m| m.is_place_move() && matches!(m.place_piece(), Piece::WhiteFlat | Piece::BlackFlat))
        .collect();
    let pool = if flats.is_empty() { &moves } else { &flats };
    let idx = rng.next_u32() as usize % pool.len();
    board.do_move(pool[idx]);
}

// ---------------------------------------------------------------------------
// tiltak TEI subprocess client
// ---------------------------------------------------------------------------

/// TEI subprocess client (also reused by `balance5` for tiltak-driven balance).
pub(crate) struct Tiltak {
    child: Child,
    stdin: BufWriter<ChildStdin>,
    stdout: BufReader<ChildStdout>,
    line: String,
}

impl Tiltak {
    pub(crate) fn spawn(path: &str, size: usize, half_komi: u8) -> io::Result<Self> {
        let mut child = Command::new(path)
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            // tiltak logs "Failed to find move difference, creating new tree" to stderr on every
            // ply (we feed full TPS, not incremental moves), which floods at scale; discard it. A
            // real crash surfaces as EOF on stdout, which the self-play loop handles.
            .stderr(Stdio::null())
            .spawn()?;
        let stdin = BufWriter::new(child.stdin.take().unwrap());
        let stdout = BufReader::new(child.stdout.take().unwrap());
        let mut t = Self { child, stdin, stdout, line: String::new() };
        t.send("tei")?;
        t.wait_for("teiok")?;
        t.send(&format!("setoption name HalfKomi value {half_komi}"))?;
        t.send("isready")?;
        t.wait_for("readyok")?;
        Ok(t)
    }

    fn send(&mut self, cmd: &str) -> io::Result<()> {
        writeln!(self.stdin, "{cmd}")?;
        self.stdin.flush()
    }

    /// Read one line (trimmed), or `None` at EOF.
    fn read_line(&mut self) -> io::Result<Option<&str>> {
        self.line.clear();
        let n = self.stdout.read_line(&mut self.line)?;
        if n == 0 {
            Ok(None)
        } else {
            Ok(Some(self.line.trim_end()))
        }
    }

    fn wait_for(&mut self, token: &str) -> io::Result<()> {
        while let Some(line) = self.read_line()? {
            if line.starts_with(token) {
                return Ok(());
            }
        }
        Err(io::Error::new(io::ErrorKind::UnexpectedEof, format!("tiltak closed before '{token}'")))
    }

    pub(crate) fn new_game(&mut self, size: usize) -> io::Result<()> {
        self.send(&format!("teinewgame {size}"))
    }

    /// Ask tiltak for the best move + STM win-probability from a TPS position.
    pub(crate) fn bestmove(&mut self, tps: &str, nodes: u64) -> io::Result<Option<(String, f64)>> {
        self.send(&format!("position tps {tps}"))?;
        self.send(&format!("go nodes {nodes}"))?;
        let mut win_prob = 0.5;
        loop {
            let line = match self.read_line()? {
                Some(l) => l,
                None => return Ok(None), // engine died
            };
            if line.starts_with("info") {
                if let Some(p) = parse_info_winprob(line) {
                    win_prob = p;
                }
            } else if let Some(rest) = line.strip_prefix("bestmove ") {
                let mv = sanitize_move(rest.split_whitespace().next().unwrap_or(""));
                if mv.is_empty() {
                    return Ok(None);
                }
                return Ok(Some((mv, win_prob)));
            }
        }
    }
}

impl Drop for Tiltak {
    fn drop(&mut self) {
        let _ = self.send("quit");
        let _ = self.child.kill();
        let _ = self.child.wait();
    }
}

/// Parse the STM win-probability from a tiltak `info ... score cp <cp> ...` line.
/// tiltak emits `cp = (win_prob * 200 - 100)`, so `win_prob = (cp + 100) / 200`.
fn parse_info_winprob(line: &str) -> Option<f64> {
    let mut it = line.split_whitespace();
    while let Some(tok) = it.next() {
        if tok == "cp" {
            let cp: f64 = it.next()?.parse().ok()?;
            return Some(((cp + 100.0) / 200.0).clamp(0.0, 1.0));
        }
    }
    None
}

/// Strip PTN annotation suffixes (tak/road/quality marks) tiltak may append, e.g. `e3+*`.
fn sanitize_move(mv: &str) -> String {
    mv.trim_end_matches(['*', '!', '?', '\'']).to_string()
}

// ---------------------------------------------------------------------------
// Self-play
// ---------------------------------------------------------------------------

/// Play `num_games`, driving one tiltak subprocess; send finished chunks to the writer thread.
fn worker(
    num_games: usize,
    cfg: &DataGen5Config,
    book: Option<Arc<Vec<String>>>,
    tx: mpsc::Sender<Vec<u8>>,
    games_done: &AtomicU64,
    positions_done: &AtomicU64,
) -> io::Result<()> {
    let mut rng = new_rng();
    let mut tiltak = Tiltak::spawn(&cfg.tiltak_path, 5, cfg.half_komi)?;
    let mut body: Vec<u8> = Vec::with_capacity(TARGET_CHUNK_BYTES + 256);
    let mut positions: Vec<(BoardData5, i16)> = Vec::new();

    for _ in 0..num_games {
        positions.clear();
        tiltak.new_game(5)?;
        // Opening: a book position (standard, move_num>=2) or an internally generated black-stack one.
        let mut board = start_board(&book, cfg.random_plies, &mut rng);

        // tiltak plays out standard Tak from the opening TPS; record each position.
        let mut plies = 0;
        let mut hit_cap = false;
        while board.game_result().is_none() {
            if plies >= cfg.max_plies {
                hit_cap = true;
                break;
            }
            let tps = format!("{:?}", board);
            let (mv_str, p) = match tiltak.bestmove(&tps, cfg.max_nodes)? {
                Some(v) => v,
                None => break, // engine produced no move; abandon this game
            };
            let mv = match GameMove::try_from_ptn(&mv_str, &board) {
                Some(m) => m,
                None => {
                    eprintln!("datagen5: could not parse tiltak move '{mv_str}' at tps '{tps}'");
                    break;
                }
            };
            let data = build_nn_repr5(&board);
            positions.push((data, score_from_winprob(p)));
            board.do_move(mv);
            plies += 1;
        }

        // Backfill the result (draw if we hit the ply cap).
        let outcome = if hit_cap {
            GameResult::Draw
        } else {
            board.game_result().unwrap_or(GameResult::Draw)
        };
        for (data, score) in positions.iter() {
            let result = result_for(data.white_to_move, outcome);
            push_entry(&mut body, data, *score, result, cfg.half_komi);
        }
        positions_done.fetch_add(positions.len() as u64, Ordering::Relaxed);

        if body.len() >= TARGET_CHUNK_BYTES {
            if tx.send(make_chunk(&body)).is_err() {
                return Ok(());
            }
            body.clear();
        }

        let n = games_done.fetch_add(1, Ordering::Relaxed) + 1;
        if n % 100 == 0 {
            eprintln!("datagen5: {n} games, {} positions", positions_done.load(Ordering::Relaxed));
        }
    }

    if !body.is_empty() {
        let _ = tx.send(make_chunk(&body));
    }
    Ok(())
}

/// Generate a tiltak self-play dataset and write it to `cfg.output`.
pub fn run(cfg: DataGen5Config) -> io::Result<()> {
    assert!(cfg.threads >= 1, "need at least one thread");
    let start = Instant::now();
    println!(
        "datagen5: {} games, {} threads, tiltak {} nodes/move, {} random plies, komi {} -> {}",
        cfg.num_games, cfg.threads, cfg.max_nodes, cfg.random_plies, cfg.half_komi, cfg.output
    );
    println!("datagen5: tiltak binary = {}", cfg.tiltak_path);

    let book = match &cfg.book_path {
        Some(p) => {
            let b = Arc::new(load_book(p)?);
            println!("datagen5: opening book = {} ({} positions, standard play)", p, b.len());
            Some(b)
        }
        None => None,
    };

    let (tx, rx) = mpsc::channel::<Vec<u8>>();
    let out_path = cfg.output.clone();
    let writer = thread::spawn(move || -> io::Result<u64> {
        let mut file = BufWriter::new(File::create(&out_path)?);
        let mut bytes = 0u64;
        while let Ok(chunk) = rx.recv() {
            file.write_all(&chunk)?;
            bytes += chunk.len() as u64;
        }
        file.flush()?;
        Ok(bytes)
    });

    let games_done = Arc::new(AtomicU64::new(0));
    let positions_done = Arc::new(AtomicU64::new(0));

    let base = cfg.num_games / cfg.threads;
    let extra = cfg.num_games % cfg.threads;
    let mut handles = Vec::new();
    for t in 0..cfg.threads {
        let games = base + if t < extra { 1 } else { 0 };
        if games == 0 {
            continue;
        }
        let tx = tx.clone();
        let cfg = cfg.clone();
        let book = book.clone();
        let games_done = games_done.clone();
        let positions_done = positions_done.clone();
        handles.push(thread::spawn(move || {
            if let Err(e) = worker(games, &cfg, book, tx, &games_done, &positions_done) {
                eprintln!("datagen5: worker {t} failed: {e}");
            }
        }));
    }
    drop(tx);

    for h in handles {
        h.join().expect("worker thread panicked");
    }
    let bytes = writer.join().expect("writer thread panicked")?;

    let secs = start.elapsed().as_secs_f64();
    let positions = positions_done.load(Ordering::Relaxed);
    println!(
        "datagen5 done: {} games, {} positions, {:.1} MB in {:.1}s ({:.0} pos/s) -> {}",
        games_done.load(Ordering::Relaxed),
        positions,
        bytes as f64 / (1024.0 * 1024.0),
        secs,
        positions as f64 / secs.max(1e-9),
        cfg.output,
    );
    Ok(())
}

// ---------------------------------------------------------------------------
// Topaz self-play (NNUE5) datagen — for iterating past the tiltak label ceiling
// ---------------------------------------------------------------------------
//
// Once the engine's own net beats tiltak, tiltak's labels cap quality. This path self-plays with
// Topaz's NNUE5 search instead (AlphaZero-style: generate with the current best net, train the next
// one). It reuses this module's TAK6 writer / opening / threading. Topaz plays the black-stack rule
// natively (forced 2xx at move_num 1), so no TPS handoff is needed, and the recorded score is
// Topaz's own search eval — already on the trainer's `eval_scale=400` sigmoid scale, no conversion.

/// Hard depth cap; the node limit normally stops the search first.
const MAX_DEPTH: usize = 30;

#[derive(Clone, Debug)]
pub struct SelfPlay5Config {
    pub num_games: usize,
    pub threads: usize,
    /// Topaz search node cap per move.
    pub max_nodes: u64,
    pub random_plies: usize,
    pub max_plies: usize,
    /// Half-komi written to the TAK6 entries (0 for the black-stack variant).
    pub half_komi: u8,
    /// Optional opening book (TPS per line, move_num>=2). If set, games start from book positions
    /// (standard play); if None, openings are generated internally (black-stack).
    pub book_path: Option<String>,
    pub output: String,
    /// Transposition-table entries per worker thread.
    pub tt_size: usize,
}

impl Default for SelfPlay5Config {
    fn default() -> Self {
        Self {
            num_games: 1000,
            threads: 4,
            max_nodes: 5000,
            random_plies: 6,
            max_plies: 120,
            half_komi: 0,
            book_path: None,
            output: "data5_self.bin".to_string(),
            tt_size: 1 << 20,
        }
    }
}

/// Self-play `num_games` with Topaz NNUE5 search; send finished chunks to the writer thread.
fn worker_selfplay(
    num_games: usize,
    cfg: &SelfPlay5Config,
    book: Option<Arc<Vec<String>>>,
    tx: mpsc::Sender<Vec<u8>>,
    games_done: &AtomicU64,
    positions_done: &AtomicU64,
) {
    let mut rng = new_rng();
    let table = HashTable::new(cfg.tt_size);
    let mut body: Vec<u8> = Vec::with_capacity(TARGET_CHUNK_BYTES + 256);
    let mut positions: Vec<(BoardData5, i16)> = Vec::new();

    for _ in 0..num_games {
        table.clear();
        positions.clear();
        // Opening: a book position (standard, move_num>=2) or an internally generated black-stack one.
        let mut board = start_board(&book, cfg.random_plies, &mut rng);

        // Self-play to game end, recording each searched position + Topaz's eval.
        let mut plies = 0;
        let mut hit_cap = false;
        while board.game_result().is_none() {
            if plies >= cfg.max_plies {
                hit_cap = true;
                break;
            }
            let mut eval = NNUE5::default();
            let mut info = SearchInfo::new(MAX_DEPTH, &table)
                .set_max_nodes(cfg.max_nodes, cfg.max_nodes)
                .quiet(true);
            let outcome = match search(&mut board, &mut eval, &mut info) {
                Some(o) => o,
                None => break,
            };
            let mv = match outcome.next() {
                Some(m) => m,
                None => break,
            };
            let data = build_nn_repr5(&board);
            let score = outcome.score().clamp(i16::MIN as i32, i16::MAX as i32) as i16;
            positions.push((data, score));
            board.do_move(mv);
            plies += 1;
        }

        let outcome = if hit_cap {
            GameResult::Draw
        } else {
            board.game_result().unwrap_or(GameResult::Draw)
        };
        for (data, score) in positions.iter() {
            let result = result_for(data.white_to_move, outcome);
            push_entry(&mut body, data, *score, result, cfg.half_komi);
        }
        positions_done.fetch_add(positions.len() as u64, Ordering::Relaxed);

        if body.len() >= TARGET_CHUNK_BYTES {
            if tx.send(make_chunk(&body)).is_err() {
                return;
            }
            body.clear();
        }

        let n = games_done.fetch_add(1, Ordering::Relaxed) + 1;
        if n % 100 == 0 {
            eprintln!("datagen5self: {n} games, {} positions", positions_done.load(Ordering::Relaxed));
        }
    }

    if !body.is_empty() {
        let _ = tx.send(make_chunk(&body));
    }
}

/// Generate a Topaz self-play dataset and write it to `cfg.output`.
pub fn run_selfplay(cfg: SelfPlay5Config) -> io::Result<()> {
    assert!(cfg.threads >= 1, "need at least one thread");
    let start = Instant::now();
    println!(
        "datagen5self: {} games, {} threads, topaz {} nodes/move, {} random plies, komi {} -> {}",
        cfg.num_games, cfg.threads, cfg.max_nodes, cfg.random_plies, cfg.half_komi, cfg.output
    );

    let book = match &cfg.book_path {
        Some(p) => {
            let b = Arc::new(load_book(p)?);
            println!("datagen5self: opening book = {} ({} positions, standard play)", p, b.len());
            Some(b)
        }
        None => None,
    };

    let (tx, rx) = mpsc::channel::<Vec<u8>>();
    let out_path = cfg.output.clone();
    let writer = thread::spawn(move || -> io::Result<u64> {
        let mut file = BufWriter::new(File::create(&out_path)?);
        let mut bytes = 0u64;
        while let Ok(chunk) = rx.recv() {
            file.write_all(&chunk)?;
            bytes += chunk.len() as u64;
        }
        file.flush()?;
        Ok(bytes)
    });

    let games_done = Arc::new(AtomicU64::new(0));
    let positions_done = Arc::new(AtomicU64::new(0));

    let base = cfg.num_games / cfg.threads;
    let extra = cfg.num_games % cfg.threads;
    let mut handles = Vec::new();
    for t in 0..cfg.threads {
        let games = base + if t < extra { 1 } else { 0 };
        if games == 0 {
            continue;
        }
        let tx = tx.clone();
        let cfg = cfg.clone();
        let book = book.clone();
        let games_done = games_done.clone();
        let positions_done = positions_done.clone();
        handles.push(thread::spawn(move || {
            worker_selfplay(games, &cfg, book, tx, &games_done, &positions_done);
            let _ = t;
        }));
    }
    drop(tx);

    for h in handles {
        h.join().expect("worker thread panicked");
    }
    let bytes = writer.join().expect("writer thread panicked")?;

    let secs = start.elapsed().as_secs_f64();
    let positions = positions_done.load(Ordering::Relaxed);
    println!(
        "datagen5self done: {} games, {} positions, {:.1} MB in {:.1}s ({:.0} pos/s) -> {}",
        games_done.load(Ordering::Relaxed),
        positions,
        bytes as f64 / (1024.0 * 1024.0),
        secs,
        positions as f64 / secs.max(1e-9),
        cfg.output,
    );
    Ok(())
}
